version: "3"
services:
  dappa:
    env_file:
      - ./docker/local.env
    image: secrets-sharing-app:local
    networks:
      - dappa
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "5000:5000"

networks:
  dappa:
    name: dappa
    external: true
