version: "3"
services:
  dappa:
    env_file:
      - ./docker/local.env
    image: secrets-sharing-app:local
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "5000:5000"
  api-test:
    depends_on:
      dappa:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./docker/api-test.Dockerfile
